### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'noise_agressiveness'

### ISSUE THREAD

**Issue by nanonomad** [rioharper/VocalForge#1]
Looking forward to trying this out.  Ran into this error after following the installation steps:

(vocal-forge) nano@DESKTOP-73RPGPM:~/VocalForge$ python refineaudio.py --raw_dir /mnt/e/hitchcock --work_dir /mnt/e/hitchcock/working
CUDA device configured correctly!
False
Traceback (most recent call last):
  File "refineaudio.py", line 867, in <module>
    remove_nonspeech(args.vad_threshold, args.noise_agressiveness)
AttributeError: 'Namespace' object has no attribute 'noise_agressiveness'

**Comment by rioharper** [comment]
oops! Sorry, I did a small update where I changed the variable name for the sake of simplicity and forgot to update that part.

I updated the repo, but you can just change line 867 from
`remove_nonspeech(args.vad_threshold, args.noise_agressiveness)`
`remove_nonspeech(args.vad_threshold, args.snr_change)`
