### ISSUE TITLE
Severe compatibility issues with PyTorch_lighting

### ISSUE THREAD

**Issue by Dannypeja** [rioharper/VocalForge#13]
This repo is an amazing idea as I haven't seen anything similar anywhere on the web. I would love to get it running!

I have been fiddling now for days to get this running. 
I am having severe issues with dependencies. In the end something fails when Nemo calls PyTorch_lightning deps. 

Have you encountered any of these issues before? I have installed everything locally as described in your repo and still encounter these issues.

Thanks!

**Comment by rioharper** [comment]
Sorry to hear that! I haven't encountered those issues personally. Would you mind giving me the full error log and what operating system/GPU you are running? 

Thanks!
