### ISSUE TITLE
Minor issue with requirements.txt re: brouhaha-vad

### ISSUE THREAD

**Issue by nanonomad** [rioharper/VocalForge#5]
WARNING: Generating metadata for package brouhaha-vad produced metadata for project name brouhaha. Fix your #egg=brouhaha-vad fragments.
Discarding https://github.com/marianne-m/brouhaha-vad/archive/main.zip: Requested brouhaha from https://github.com/marianne-m/brouhaha-vad/archive/main.zip (from -r requirements.txt (line 20)) has inconsistent name: expected 'brouhaha-vad', but metadata has 'brouhaha'

Edited requirements.txt to change brouhaha-vad to brouhaha and things seem to install fine.

**Comment by rioharper** [comment]
they must have changed their name of their github repo, thanks for the heads up! Ill change it.
