### ISSUE TITLE
Issues after installing libraries

### ISSUE THREAD

**Issue by scape7575** [rioharper/VocalForge#7]
Hi! First of all, I am very amazed by the concept of this repo, to be able to create a dataset seemingly automatically is fantastic! Unfortunately I am having a slight issue with the audio_demo.py script. I am getting a module error as such: 

`(VocalForge) root@user:/home/user/VocalForge# python3 audio_demo.py --help
Traceback (most recent call last):
  File "audio_demo.py", line 3, in <module>
    from audio.audio_utils import create_core_folders, download_videos, create_samples
  File "/home/user/VocalForge/audio/__init__.py", line 5, in <module>
    from .export_audio import ExportAudio
  File "/home/scape7575/VocalForge/audio/export_audio.py", line 6, in <module>
    from df.enhance import enhance, init_df, load_audio, save_audio
ModuleNotFoundError: No module named 'df'`

No module named df, is this because of a broken dependency? I would really like to start using this! Thank you

**Comment by rioharper** [comment]
Hello!

Sorry for the all the confusion. About a month ago there was a large rewrite of the code for one of the libraries I was using for this project which led this code to be defunct. I took it as an opportunity to start rewrite my code to make it better and more optimized, which of course spiraled into a something way bigger than originally anticipated. I really have only updated the audio processing section of `VocalForge`, which doesn't include the text processing (transcription, metadata, etc) but that is next on the chopping block.

Anyways, excuses aside, I just published the most recent update on the [development branch](https://github.com/rioharper/VocalForge/tree/dev) which you are free to use. The [audio_demo.ipynb](https://github.com/rioharper/VocalForge/blob/dev/audio_demo.ipynb) should give you a good enough guide for the new and existing features. (now you can pip install VocalForge!). If you got any questions though through the process, let me know and ill respond ASAP.

Thanks for your patience,
Rio

**Comment by scape7575** [comment]
Hello!

First, thank you for pointing me in the right direction! Following the audio_demo.ipynb, I was able to get it running as well as pip installing VocalForge which is fantastic. I just had a question, now the goal of the audio_demo.ipynb is not to actually create a dataset correct? As in it will not create the metadata.csv in LJSpeech format and such, how do I go about doing that by adjusting on the script? Thank you once more!

**Comment by rioharper** [comment]
Glad to hear it helped! To answer your question, the current section cleans
up data to be used for the dataset curation portion of VocalForge. I dont
have a full tutorial for this section (probably coming later this week) but
if you want to try it yourself without a ton of documentation I just
updated text_demo.ipynb on the dev branch.

Give that a shot! You may have to work through some errors yourself.
