### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by gnekt** [rioharper/VocalForge#8]
Hello :smile: 
Since I love this idea, I was thinking to be a contributor.
I Forked the repository and synced with dev branch.
I was planning (for my personal understanding of the whole code) to realize a CLI interface since in this branch I saw only notebooks.

----

It is okay for u?

**Comment by rioharper** [comment]
Sorry for not writing sooner!

Absolutely. Would love to see how it turns out! Currently focusing on an API because I find it fits my needs better, but a good CLI would be appreciated I'm sure.

If you need any clarification on my code, let me know.
